package com.example.berkcirisci.alphafitness;

import com.j256.ormlite.field.DatabaseField;

/**
 * Created by berkcirisci on 5.8.2016.
 */
public class WorkoutPoint {

    // id is generated by the database and set on the object
    @DatabaseField(generatedId = true)
    int id;

    @DatabaseField
    double latitude;

    @DatabaseField
    double longitude;

    @DatabaseField
    long currentTime;

    @DatabaseField(foreign = true, foreignAutoRefresh = true)
    Workout workout;

    public WorkoutPoint() {
        // needed by ormlite
    }

    public WorkoutPoint(double latitude, double longitude, Workout workout) {
        currentTime = System.currentTimeMillis();
        this.latitude = latitude;
        this.longitude = longitude;
        this.workout = workout;
    }

    public int getId() {
        return id;
    }

    public double getLatitude() {
        return latitude;
    }

    public double getLongitude() {
        return longitude;
    }

    public long getCurrentTime() {
        return currentTime;
    }

    public Workout getWorkout() {
        return workout;
    }
}
