package com.example.berkcirisci.alphafitness;

import com.j256.ormlite.field.DatabaseField;

/**
 * Created by berkcirisci on 5.8.2016.
 */
public class Workout {

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    int id;

    public Workout() {
        // needed by ormlite
    }

    public int getId() {
        return id;
    }
}
